info: 
  description: This is a find my salon spring boot roject
  
server:
  port: 8081
  servlet:
    context-path: /findmysalon
  
spring: 
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
  application:
    name: findMySalon
  profiles:
    active: default

  http:
    converters:
      preferred-json-mapper: gson
      
  mail:
    host: smtp.gmail.com
    port: 587
      
management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.spg.salon: DEBUG