spj:
  services:
    oauthHost: https://authorization-spj.herokuapp.com/findmysalon

security:
  oauth2:
    resource:
      token-info-uri: https://authorization-spj.herokuapp.com/findmysalon/oauth/check_token