info:
  description: This is a find my salon spring boot project

server:
  port: ${PORT:8081}
  servlet:
    context-path: /findmysalon

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
  application:
    name: findMySalon
  profiles:
    active: default
  cloud:
    stream:
      bindings:
        user-registered-out:
          destination: user-registered

  flyway:
    baseline-on-migrate: true
    schemas:
      - usa

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.spg.salon: DEBUG

spj:
  services:
    authenticate: /findmysalon/oauth/token
    oauthHost: http://localhost:8080/findmysalon

security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8080/findmysalon/oauth/check_token
    client:
      client-id: spj
      client-secret: thisissecret