info: 
  description: This is a find my salon spring boot project
  
server:
  port: ${PORT:8081}
  servlet:
    context-path: /findmysalon
  
spring: 
  application:
    name: findMySalon
  profiles:
    active: default
  
  flyway:
    enabled: false 
      
  mail:
    host: smtp.gmail.com
    port: 587
  
management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.spg.salon: DEBUG
    
spj:
  application:
    id: spj
    password: thisissecret
  services:
    authenticate: /findmysalon/oauth/token